fix(charts/dex): fix render error caused by #71
In chart version 0.6.6 (#71), the template rendering broke because it tries to use `.Values.topologySpreadConstraints` while still within the `.Values.affinity` scope. This lead to an error like the following:

```
Error: template: dex/templates/deployment.yaml:126:22: executing "dex/templates/deployment.yaml" at <.Values.topologySpreadConstraints>: nil pointer evaluating interface {}.topologySpreadConstraints
```

Signed-off-by: Branden Cash <203336+ammmze@users.noreply.github.com>